export const displayTheme = {
  colors: {
    bg: '#0B0B0C',
    surface: '#121214',
    surfaceRaised: '#17171A',
    hairline: 'rgba(255,255,255,0.08)',
    hairlineStrong: 'rgba(255,255,255,0.16)',
    text: '#F4F1EA',
    textMuted: '#A7A399',
    textFaint: '#6F6B63',
    gold: '#C9A24B',
    goldSoft: '#E3C77A',
    goldMuted: 'rgba(201,162,75,0.14)',
    green: '#1E8F63',
    greenMuted: 'rgba(30,143,99,0.14)',
    pageBackground: 'radial-gradient(ellipse at center, transparent 45%, rgba(0,0,0,0.22) 100%), linear-gradient(180deg, #121214 0%, #0B0B0C 32%, #0B0B0C 100%)',
    photoFade: 'linear-gradient(transparent, rgba(0,0,0,0.2))',
    confettiWhite: '#FFFFFF',
  },
  fonts: {
    sans: 'Inter, sans-serif',
    serif: '"Playfair Display", Georgia, serif',
  },
  sizes: {
    canvasWidth: 1920,
    canvasHeight: 1080,
    safeMargin: 64,
    headerHeight: 96,
    photoSm: 56,
    photoMd: 96,
    photoLg: 200,
    photoXl: 420,
  },
} as const

export const displayCssVars = {
  '--display-bg': displayTheme.colors.bg,
  '--display-surface': displayTheme.colors.surface,
  '--display-surface-raised': displayTheme.colors.surfaceRaised,
  '--display-hairline': displayTheme.colors.hairline,
  '--display-hairline-strong': displayTheme.colors.hairlineStrong,
  '--display-text': displayTheme.colors.text,
  '--display-text-muted': displayTheme.colors.textMuted,
  '--display-text-faint': displayTheme.colors.textFaint,
  '--display-gold': displayTheme.colors.gold,
  '--display-gold-soft': displayTheme.colors.goldSoft,
  '--display-gold-muted': displayTheme.colors.goldMuted,
  '--display-green': displayTheme.colors.green,
  '--display-green-muted': displayTheme.colors.greenMuted,
  '--display-page-background': displayTheme.colors.pageBackground,
  '--display-photo-fade': displayTheme.colors.photoFade,
  '--display-font-sans': displayTheme.fonts.sans,
  '--display-font-serif': displayTheme.fonts.serif,
  '--display-safe-margin': `${displayTheme.sizes.safeMargin}px`,
  '--display-header-height': `${displayTheme.sizes.headerHeight}px`,
  '--display-photo-sm': `${displayTheme.sizes.photoSm}px`,
  '--display-photo-md': `${displayTheme.sizes.photoMd}px`,
  '--display-photo-lg': `${displayTheme.sizes.photoLg}px`,
  '--display-photo-xl': `${displayTheme.sizes.photoXl}px`,
} as React.CSSProperties